#!/bin/bash

# CAREFUL! This overwrites existing files!
ln -sf "$HOME/.dev-setup/dotfiles/aliases/.aliases" "$HOME/.aliases" 
ln -sf "$HOME/.dev-setup/dotfiles/bash/.bashrc" "$HOME/.bashrc"
ln -sf "$HOME/.dev-setup/dotfiles/config/.config/autostart/gedit.desktop" "$HOME/.config/autostart/gedit.desktop"
ln -sf "$HOME/.dev-setup/dotfiles/config/.config/zellij/config.kdl" "$HOME/.config/zellij/config.kdl"
mkdir ~/.config/zellij/layouts
ln -sf "$HOME/.dev-setup/dotfiles/config/.config/zellij/layouts/default.kdl" "$HOME/.config/zellij/layouts/default.kdl"
ln -sf "$HOME/.dev-setup/dotfiles/git/.git-commit-message-template.txt" "$HOME/.git-commit-message-template.txt"
ln -sf "$HOME/.dev-setup/dotfiles/scripts/.local/bin/canvas.html" "$HOME/.local/bin/canvas.html"
ln -sf "$HOME/.dev-setup/dotfiles/scripts/.local/bin/canvas.sh" "$HOME/.local/bin/canvas.sh"
ln -sf "$HOME/.dev-setup/dotfiles/scripts/.local/bin/dev-morning.sh" "$HOME/.local/bin/dev-morning.sh"
ln -sf "$HOME/.dev-setup/dotfiles/scripts/.local/bin/git-bisect-find-bug.sh" "$HOME/.local/bin/git-bisect-find-bug.sh"
ln -sf "$HOME/.dev-setup/dotfiles/scripts/.local/bin/switch-window.sh" "$HOME/.local/bin/switch-window.sh"
ln -sf "$HOME/.dev-setup/dotfiles/scripts/.local/bin/timer.sh" "$HOME/.local/bin/timer.sh"
ln -sf "$HOME/.dev-setup/dotfiles/scripts/.local/bin/uptimes.sh" "$HOME/.local/bin/uptimes.sh"
ln -sf "$HOME/.dev-setup/dotfiles/scripts/.local/bin/code-review.sh" "$HOME/.local/bin/code-review.sh"
ln -sf "$HOME/.dev-setup/dotfiles/zsh/.zshrc" "$HOME/.zshrc"
ln -sf "$HOME/.dev-setup/dotfiles/cheatsheets/.local/share/navi/cheats/docker.cheat" "$HOME/.local/share/navi/cheats/docker.cheat"
ln -sf "$HOME/.dev-setup/dotfiles/cheatsheets/.local/share/navi/cheats/ripgrep.cheat" "$HOME/.local/share/navi/cheats/ripgrep.cheat"
ln -sf "$HOME/.dev-setup/dotfiles/cheatsheets/.local/share/navi/cheats/git.cheat" "$HOME/.local/share/navi/cheats/git.cheat"
ln -sf "$HOME/.dev-setup/dotfiles/cheatsheets/.local/share/navi/cheats/psql.cheat" "$HOME/.local/share/navi/cheats/psql.cheat"
ln -sf "$HOME/.dev-setup/dotfiles/cheatsheets/.local/share/navi/cheats/kubectl.cheat" "$HOME/.local/share/navi/cheats/kubectl.cheat"
ln -sf "$HOME/.dev-setup/dotfiles/cheatsheets/.local/share/navi/cheats/maven.cheat" "$HOME/.local/share/navi/cheats/maven.cheat"
ln -sf "$HOME/.dev-setup/dotfiles/cheatsheets/.local/share/navi/cheats/rainfrog.cheat" "$HOME/.local/share/navi/cheats/rainfrog.cheat"
mkdir ~/.githooks
ln -sf "$HOME/.dev-setup/dotfiles/git/.githooks/prepare-commit-msg" "$HOME/.githooks/prepare-commit-msg"
ln -sf "$HOME/.dev-setup/dotfiles/git/.gitconfig" "$HOME/.gitconfig"
ln -sf "$HOME/.dev-setup/dotfiles/git/.gitconfig-personal" "$HOME/.gitconfig-personal"